erDiagram
  BLOOM_REPORT ||--o{ CASE : Case_ID
  BLOOM_REPORT ||--o{ RESPONSE : Bloom_Report_ID
  BLOOM_REPORT ||--o{ RESULT : Bloom_Report_ID
  CASE ||--o{ RESPONSE : Case_ID
  CASE ||--o{ RESULT : Case_ID

